# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17cbc8ca74a2cf39c0644106122373e06fea4b035a899406872d0048eb0db7ab50ac5c54018308c1db81500f531116844af2281b9b1978a7eb5307ceda7c2fa4

test:
  secret_key_base: ddc287650a472207c23404a001ebc06b0a04c3cfe1764440e382b1c8372b3a68fd2dcacf5164b43aefb0e95203c3c58800ea793482b4c1da2d6e779e430dceff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
